server:
  port: 9020

spring:
  application:
    name: mc-spc-sales-service
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mcspcsales?charset=utf8mb4&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #最大活跃数
      maxActive: 20
      #初始化数量
      initialSize: 1
      #最大连接等待超时时间
      maxWait: 60000
      #打开PSCache，并且指定每个连接PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
      #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
      filters: stat, wall, log4j
#    hikari:
#      maximum-pool-size: 20
#      minimum-idle: 5
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    name: C:\work\jusstech\dev\chongstudy\log\mc-spc-sales-service.log
    max-history: 7
    max-size: 10MB
  level:
    root: info
    com.chong.mcspcgoodsservice.dao: debug

exchange-name:
  mc-spc-order-service: exchange.order
routing-key:
  order-create:
    mc-spc-order-service: queue.order.create.mc-spc-order-service
  order-cancel:
    mc-spc-order-service: queue.order.cancel.mc-spc-order-service
  order-create-result:
    mc-spc-sales-service: queue.order.create.result.mc-spc-sales-service
  order-cancel-result:
    mc-spc-sales-service: queue.order.cancel.result.mc-spc-sales-service

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.chong.mcspcgoodsservice.entity
